name: Test cocos2d-x Source Code

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-macos:
    strategy:
      matrix:
        os: [ macos-15 ]
        arch: [ x64 arm64 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Initial Project
        run: |
          # cmake -B b -S . -GXcode
          cmake -B b -S .

      - name: Build tests
        run: |
          cmake --build b --target cpp-tests

  test-windows:
    strategy:
      matrix:
        os: [ windows-2022 ]
        arch: [ x64 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Initial Project
        run: |
          cmake -B b -S . -G "Visual Studio 17 2022" -A win32

      - name: Build tests
        run: |
          cmake --build b --target cpp-tests
