name: Unit Test

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test-macos:
    strategy:
      matrix:
        os:
          - macos-15-intel
        arch:
          - x64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Project
        run: |
          cmake -B b -S . -GXcode

      - name: Build Unit Tests
        run: |
          cmake --build b --target cpp-tests

  test-windows:
    strategy:
      matrix:
        os:
          - windows-2022
        arch:
          - x64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Project
        run: |
          cmake -B b -S . -G "Visual Studio 17 2022" -A win32

      - name: Build Unit Tests
        run: |
          cmake --build b --target cpp-tests
